/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Card } from "./Card";
export type { CardRetail } from "./CardRetail";
export type { Collection } from "./Collection";
export type { Main } from "./Main";
export type { NFTPokemonBooster } from "./NFTPokemonBooster";
